const bookstoreData = [
    // Fiction Books
    {
      bookID: "1",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      category: "Fiction",
      genre: "Classic",
      publicationDate: "1960-07-11",
      isbn: "9780061120084",
      price: 7.99,
      stock: 35,
      description: "A novel about racial injustice in the Deep South.",
      coverImage: "https://example.com/tokillamockingbird.jpg",
      rating: 4.8,
      publisher: "J.B. Lippincott & Co.",
      language: "English",
      format: "Paperback",
      pages: 324,
      sold: 15,
    },
    {
      bookID: "2",
      title: "1984",
      author: "George Orwell",
      category: "Fiction",
      genre: "Dystopian",
      publicationDate: "1949-06-08",
      isbn: "9780451524935",
      price: 9.99,
      stock: 60,
      description: "A dystopian novel set in a totalitarian society under constant surveillance.",
      coverImage: "https://example.com/1984.jpg",
      rating: 4.6,
      publisher: "Secker & Warburg",
      language: "English",
      format: "Hardcover",
      pages: 328,
      sold: 20,
    },
    {
      bookID: "3",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      category: "Fiction",
      genre: "Classic",
      publicationDate: "1925-04-10",
      isbn: "9780743273565",
      price: 10.99,
      stock: 50,
      description: "A novel about the American dream.",
      coverImage: "https://example.com/thegreatgatsby.jpg",
      rating: 4.7,
      publisher: "Scribner",
      language: "English",
      format: "Hardcover",
      pages: 180,
      sold: 25,
    },
    {
      bookID: "4",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      category: "Fiction",
      genre: "Romance",
      publicationDate: "1813-01-28",
      isbn: "9780141439518",
      price: 6.99,
      stock: 45,
      description: "A classic tale of love and manners in Georgian England.",
      coverImage: "https://example.com/prideandprejudice.jpg",
      rating: 4.5,
      publisher: "T. Egerton, Whitehall",
      language: "English",
      format: "Paperback",
      pages: 432,
      sold: 18,
    },
    {
      bookID: "5",
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      category: "Fiction",
      genre: "Coming-of-age",
      publicationDate: "1951-07-16",
      isbn: "9780316769488",
      price: 8.49,
      stock: 55,
      description: "A novel about teenage angst and alienation.",
      coverImage: "https://example.com/thecatcherintherye.jpg",
      rating: 4.4,
      publisher: "Little, Brown and Company",
      language: "English",
      format: "Paperback",
      pages: 224,
      sold: 30,
    },
    {
      bookID: "6",
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      category: "Fiction",
      genre: "Fantasy",
      publicationDate: "1954-07-29",
      isbn: "9780618640157",
      price: 14.99,
      stock: 40,
      description: "An epic fantasy saga set in the fictional world of Middle-earth.",
      coverImage: "https://example.com/thelordoftherings.jpg",
      rating: 4.9,
      publisher: "Houghton Mifflin",
      language: "English",
      format: "Hardcover",
      pages: 1178,
      sold: 35,
    },
    {
      bookID: "7",
      title: "Harry Potter and the Sorcerer's Stone",
      author: "J.K. Rowling",
      category: "Fiction",
      genre: "Fantasy",
      publicationDate: "1997-06-26",
      isbn: "9780590353427",
      price: 11.99,
      stock: 30,
      description: "The first book in the Harry Potter series.",
      coverImage: "https://example.com/harrypotter.jpg",
      rating: 4.8,
      publisher: "Bloomsbury Publishing",
      language: "English",
      format: "Paperback",
      pages: 320,
      sold: 28,
    },
    {
      bookID: "8",
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      category: "Fiction",
      genre: "Fantasy",
      publicationDate: "1937-09-21",
      isbn: "9780618260300",
      price: 9.99,
      stock: 25,
      description: "A fantasy novel about the journey of Bilbo Baggins.",
      coverImage: "https://example.com/thehobbit.jpg",
      rating: 4.7,
      publisher: "Houghton Mifflin",
      language: "English",
      format: "Paperback",
      pages: 310,
      sold: 20,
    },
    {
      bookID: "9",
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      category: "Fiction",
      genre: "Science Fiction",
      publicationDate: "1953-10-19",
      isbn: "9781451673319",
      price: 8.99,
      stock: 20,
      description: "A dystopian novel about a future society where books are banned.",
      coverImage: "https://example.com/fahrenheit451.jpg",
      rating: 4.6,
      publisher: "Ballantine Books",
      language: "English",
      format: "Paperback",
      pages: 249,
      sold: 10,
    },
    {
      bookID: "10",
      title: "Moby-Dick",
      author: "Herman Melville",
      category: "Fiction",
      genre: "Adventure",
      publicationDate: "1851-10-18",
      isbn: "9780142437247",
      price: 10.49,
      stock: 30,
      description: "A novel about Captain Ahab's obsessive quest to kill the white whale, Moby Dick.",
      coverImage: "https://example.com/mobydick.jpg",
      rating: 4.4,
      publisher: "Harper & Brothers",
      language: "English",
      format: "Paperback",
      pages: 624,
      sold: 25,
    },
    {
      bookID: "11",
      title: "Jane Eyre",
      author: "Charlotte Brontë",
      category: "Fiction",
      genre: "Gothic",
      publicationDate: "1847-10-16",
      isbn: "9780141441146",
      price: 7.49,
      stock: 40,
      description: "A novel about the struggles and triumphs of a young orphan girl.",
      coverImage: "https://example.com/janeeyre.jpg",
      rating: 4.5,
      publisher: "Smith, Elder & Co.",
      language: "English",
      format: "Paperback",
      pages: 532,
      sold: 18,
    },
    {
      bookID: "12",
      title: "Brave New World",
      author: "Aldous Huxley",
      category: "Fiction",
      genre: "Dystopian",
      publicationDate: "1932-10-27",
      isbn: "9780060850524",
      price: 8.99,
      stock: 35,
      description: "A dystopian novel set in a future world where people are controlled through technology and conditioning.",
      coverImage: "https://example.com/bravenewworld.jpg",
      rating: 4.3,
      publisher: "Chatto & Windus",
      language: "English",
      format: "Paperback",
      pages: 288,
      sold: 12,
    },
    {
        bookID: "13",
        title: "The Handmaid's Tale",
        author: "Margaret Atwood",
        category: "Fiction",
        genre: "Dystopian",
        publicationDate: "1985-09-17",
        isbn: "9780385490818",
        price: 9.49,
        stock: 28,
        description: "A dystopian novel set in a totalitarian society where women are oppressed.",
        coverImage: "https://example.com/thehandmaidstale.jpg",
        rating: 4.7,
        publisher: "McClelland & Stewart",
        language: "English",
        format: "Paperback",
        pages: 311,
        sold: 17,
      },
      {
        bookID: "14",
        title: "One Hundred Years of Solitude",
        author: "Gabriel García Márquez",
        category: "Fiction",
        genre: "Magical Realism",
        publicationDate: "1967-05-30",
        isbn: "9780060883287",
        price: 11.99,
        stock: 32,
        description: "A novel about the Buendía family's generations in the fictional town of Macondo.",
        coverImage: "https://example.com/onehundredyearsofsolitude.jpg",
        rating: 4.8,
        publisher: "Harper & Row",
        language: "English",
        format: "Paperback",
        pages: 417,
        sold: 20,
      },
      {
        bookID: "15",
        title: "The Road",
        author: "Cormac McCarthy",
        category: "Fiction",
        genre: "Post-apocalyptic",
        publicationDate: "2006-09-26",
        isbn: "9780307387899",
        price: 10.99,
        stock: 20,
        description: "A father and son's journey through a post-apocalyptic America.",
        coverImage: "https://example.com/theroad.jpg",
        rating: 4.5,
        publisher: "Alfred A. Knopf",
        language: "English",
        format: "Paperback",
        pages: 287,
        sold: 15,
      },
      {
        bookID: "16",
        title: "The Hitchhiker's Guide to the Galaxy",
        author: "Douglas Adams",
        category: "Fiction",
        genre: "Science Fiction",
        publicationDate: "1979-10-12",
        isbn: "9780345391803",
        price: 8.99,
        stock: 25,
        description: "A comedic science fiction series about the adventures of Arthur Dent.",
        coverImage: "https://example.com/hitchhikersguidetothegalaxy.jpg",
        rating: 4.6,
        publisher: "Pan Books",
        language: "English",
        format: "Paperback",
        pages: 224,
        sold: 18,
      },
      {
        bookID: "17",
        title: "The Alchemist",
        author: "Paulo Coelho",
        category: "Fiction",
        genre: "Philosophical",
        publicationDate: "1988-01-01",
        isbn: "9780062315007",
        price: 9.99,
        stock: 30,
        description: "A philosophical novel about a young Andalusian shepherd named Santiago.",
        coverImage: "https://example.com/thealchemist.jpg",
        rating: 4.7,
        publisher: "HarperOne",
        language: "English",
        format: "Paperback",
        pages: 208,
        sold: 22,
      },
      {
        bookID: "18",
        title: "Gone with the Wind",
        author: "Margaret Mitchell",
        category: "Fiction",
        genre: "Historical",
        publicationDate: "1936-06-30",
        isbn: "9781416548898",
        price: 12.49,
        stock: 18,
        description: "A historical romance set during the American Civil War and Reconstruction era.",
        coverImage: "https://example.com/gonewiththewind.jpg",
        rating: 4.4,
        publisher: "Macmillan Publishers",
        language: "English",
        format: "Hardcover",
        pages: 1037,
        sold: 12,
      },
      {
        bookID: "19",
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        category: "Fiction",
        genre: "Gothic",
        publicationDate: "1890-07-01",
        isbn: "9780486278070",
        price: 6.99,
        stock: 22,
        description: "A philosophical novel about the consequences of vanity and debauchery.",
        coverImage: "https://example.com/pictureofdoriangray.jpg",
        rating: 4.3,
        publisher: "Ward, Lock & Co.",
        language: "English",
        format: "Paperback",
        pages: 250,
        sold: 16,
      },
      {
        bookID: "20",
        title: "Catch-22",
        author: "Joseph Heller",
        category: "Fiction",
        genre: "Satire",
        publicationDate: "1961-11-10",
        isbn: "9780684833392",
        price: 8.99,
        stock: 27,
        description: "A satirical novel about the absurdities of war and bureaucracy.",
        coverImage: "https://example.com/catch22.jpg",
        rating: 4.5,
        publisher: "Simon & Schuster",
        language: "English",
        format: "Paperback",
        pages: 453,
        sold: 24,
      },
      {
        bookID: "21",
        title: "A Clockwork Orange",
        author: "Anthony Burgess",
        category: "Fiction",
        genre: "Dystopian",
        publicationDate: "1962-09-21",
        isbn: "9780393312836",
        price: 7.99,
        stock: 23,
        description: "A dystopian novella about free will and the morality of violence.",
        coverImage: "https://example.com/aclockworkorange.jpg",
        rating: 4.4,
        publisher: "W. W. Norton & Company",
        language: "English",
        format: "Paperback",
        pages: 213,
        sold: 19,
      },
      {
        bookID: "22",
        title: "The Count of Monte Cristo",
        author: "Alexandre Dumas",
        category: "Fiction",
        genre: "Adventure",
        publicationDate: "1844-08-28",
        isbn: "9780141392462",
        price: 9.49,
        stock: 26,
        description: "An adventure novel about a man's quest for revenge after being falsely imprisoned.",
        coverImage: "https://example.com/countofmontecristo.jpg",
        rating: 4.6,
        publisher: "Pétion",
        language: "English",
        format: "Paperback",
        pages: 1243,
        sold: 21,
      },
]
export default bookstoreData;
